# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0609bc184ab18f53c6fa2e4c559c69b879cb10ad6576becc09d77427eb8a4537799a014c04d2982cc8211de287db15f9b1f0900bde7dc91c02bf0ad25c5f4d82

test:
  secret_key_base: 76f7b0d9af3439dfd1055525a450823c67c6189936f2edeecfec1039d5aeaad52e4b88af8e0e684af42a69d24e21c08d3105836c3bb40e3182a66c86e28d0681

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
